### ISSUE TITLE
Cut and paste error in project descriptions?

### ISSUE THREAD

**Issue by tnabtaf** [elixir-europe/BioHackathon-projects-2019#1]
The text in this project does not appear to line up with the title:
* [Development of a Pulsar toolkit](https://github.com/elixir-europe/BioHackathon-projects-2019/tree/master/projects/17)

The text for the Pulsar project appears to be in this project:
* [Updating the Galaksio workflow management interface for Galaxy and migrating it to Vue.js](https://github.com/elixir-europe/BioHackathon-projects-2019/tree/master/projects/19)

And others are swapped as well.

**Comment by nsoranzo** [comment]
Ping @ricardoaat

**Comment by ricardoaat** [comment]
Hi @tnabtaf and @nsoranzo, thank you for noticing this. I have updated the projects they should have now the correct information. Let me know if its ok now so I can close this issue

**Comment by nsoranzo** [comment]
@ricardoaat Thanks for fixing it, I have checked some project descriptions and they seems OK apart from https://github.com/elixir-europe/BioHackathon-projects-2019/tree/master/projects/1 which seems to contain 2 separate projects which I don't think makes sense to merge.

**Comment by tnabtaf** [comment]
@ricardoaat I checked about 10 of them.  Everyone I looked at was good.  Thanks for the quick fix.

**Comment by ricardoaat** [comment]
@tnabtaf Thank you for noticing those. Closing this now.

**Comment by nsoranzo** [comment]
>  https://github.com/elixir-europe/BioHackathon-projects-2019/tree/master/projects/1 seems to contain 2 separate projects which I don't think makes sense to merge.

@ricardoaat This seems to be still the case, are you sure that "Interoperable Workflows for Communities" and "ELIXIR Data Stewardship Wizard: Templating Data Management Plans and integrating Software Management" were meant to be merged?
