### ISSUE TITLE
Add overview of projects (at least number and title)?

### ISSUE THREAD

**Issue by schymane** [elixir-europe/BioHackathon-projects-2019#16]
Folder structure with just numbers is very hard to navigate if you don't know the number ... 
https://github.com/elixir-europe/BioHackathon-projects-2019/tree/master/projects

**Comment by egonw** [comment]
Yes, was thinking the same thing. Let's add this to the root README.

**Comment by ricardoaat** [comment]
Project name and number can be found [here](https://www.biohackathon-europe.org/projects.html). Changing the folder name would break the links there.

**Comment by egonw** [comment]
Yes, for clarity, I meant: let's add a list in the README (but keep the current folder names).

**Comment by yochannah** [comment]
I think egon's right that having a link to the relevant number in the readme would help a lot - that's where we'll be editing it :)

**Comment by schymane** [comment]
Yes I completely agree, README would be great, not changing folder names!

**Comment by egonw** [comment]
The seed has been picked up. I think we can close this one now.
