### ISSUE TITLE
Improve the FAIR metrics of existing BridgeDb ID mapping databases

### ISSUE THREAD

**Issue by egonw** [elixir-europe/BioHackathon-projects-2019#27]
Making them more findable, accesible, interoperable, and reusable.

**Comment by egonw** [comment]
There are now two API methods, `config` and `properties` (actually, one for each species), which just give a text representation. These things should support a semantic web representations too, e.g. with VoID. It could be a separate method or use content negotiation.

**Comment by DeniseSl22** [comment]
I'm working on an implementation for metabolite mappings, using Neo4j (where I can use labels on the edges to show from which source the mapping is coming). I think every mapping file we have now (genes+proteins, metabolites, interactions) are based on different code and databases; would it be feasible to have a "one size fits all" approach?
