### ISSUE TITLE
Add more examples on BridgeDb SPARQL for WikiPathways

### ISSUE THREAD

**Issue by DeniseSl22** [elixir-europe/BioHackathon-projects-2019#40]
Over last year @egonw and me added quite some more (metabolite) mappings to the WikiPathways RDF, originating from BridgeDb; we should add some more example queries so it's easier for people to use those mappings in the RDF.

**Comment by DeniseSl22** [comment]
Added first [one](https://www.wikipathways.org/index.php/Help:WikiPathways_Sparql_queries#Count_how_many_genes_from_a_list_occur_in_one_or_more_pathways), which uses HGNC gene name mappings and counts the occurrence of a list of genes within the collection of Human pathways.

**Comment by egonw** [comment]
This can be a section here: https://wikipathways.github.io/WikiPathways-SPARQL-book/
