### ISSUE TITLE
Add disease ID mappings to BridgeDb

### ISSUE THREAD

**Issue by DeniseSl22** [elixir-europe/BioHackathon-projects-2019#46]
For now, we have local mapping files for genes+protein IDs, metabolites and interactions.
I believe there are quite some projects here also working on (rare) diseases.
So I've started to create the [code](https://github.com/DeniseSl22/create-bridgedb-diseases) to create these mappings, based on Wikidata. Tests in [Jenkins](https://jenkins.bigcat.unimaas.nl/job/Disease%20ID%20Mapping%20Database/) are green now, so time to extend the approach. The code now works for:
- Wikidata ID
- OMIM ID
- Disease Ontology ID

I would like to add the following (but need to make some changes to main BridgeDb code to accommodate for new databases which were previously not supported/available):
- [x] Disease Ontology ID
- [x] UMLS CUI
- [x] OrphaNet ID (at least on of the projects here is working with that database)
- [x] MeSH descriptor ID

These databases will be added separately (combining -CM and regular form):
- [x] ICD 9
- [x] ICD 10
- [x] ICD 11

After these are available in BridgeDb, I will write the remaining code to add the databases mentioned above.

If there is anyone who has a database with disease IDs (and willing to share these CC0), or is missing some database which is part of Wikidata already, please let me know so I can add that as well!

**Comment by egonw** [comment]
@larsjuhljensen came over this morning, and requests also adding ICD 9 and ICD 10 identifiers, which should be in Wikidata too.

**Comment by DeniseSl22** [comment]
Update: (Human) Disease Ontology has been:
- Added to BridgeDb disease mapping file
- Tested locally in PathVisio with new bridgedb.jars (from series/2.3 branch).
- Build is also stable in Jenkins!

Regarding adding the ICD 9/10 as a database (which we are also in favor off!) @larsjuhljensen : Would you want both (and also be able to trace from which classification systems the ID originates)? I saw several manners in which these IDs are modeled in Wikidata (even saw ICD 11), so could use some input from someone that knows more on this topic :)

**Comment by DeniseSl22** [comment]
UMLS CUI is now also part of the mappings, recognised in PV (with new bridgedb.jars), and stable build in Jenkins.

**Comment by DeniseSl22** [comment]
And the same for Orphanet!

**Comment by DeniseSl22** [comment]
Mesh is also in now!

**Comment by DeniseSl22** [comment]
Also ICD9,10,11 are added now (had to perform quite some curation on ICD10 obtained from Russian Wikipedia :( ).
